PRESETS = {
    "Cozy Vinyl": {
        "time_stretch": 0.92,
        "pitch_shift": -2.0,
        "highpass_hz": 30,
        "lowpass_hz": 14000,
        "bass_db": 2.5,
        "highshelf_freq": 12000,
        "highshelf_db": -1.5,
        "saturation": 0.5,
        "compression": 0.25,
        "bitcrush": 0.0,
        "wow_flutter": 0.25,
        "stereo_width": 1.0,
        "noise": 0.08,
        "reverb": 0.2,
        "limiter": 0.95,
    },
    "Tape Bedroom": {
        "time_stretch": 0.9,
        "pitch_shift": -3.0,
        "highpass_hz": 30,
        "lowpass_hz": 12000,
        "bass_db": 3.0,
        "highshelf_freq": 10000,
        "highshelf_db": -2.5,
        "saturation": 0.65,
        "compression": 0.25,
        "bitcrush": 0.0,
        "wow_flutter": 0.5,
        "stereo_width": 0.85,
        "noise": 0.12,
        "reverb": 0.15,
        "limiter": 0.95,
    },
    "Rainy Night": {
        "time_stretch": 0.95,
        "pitch_shift": -1.0,
        "highpass_hz": 30,
        "lowpass_hz": 12000,
        "bass_db": 2.0,
        "highshelf_freq": 10000,
        "highshelf_db": -2.0,
        "saturation": 0.4,
        "compression": 0.2,
        "bitcrush": 0.0,
        "wow_flutter": 0.2,
        "stereo_width": 1.2,
        "noise": 0.06,
        "reverb": 0.4,
        "limiter": 0.95,
    },
    "Chill Study": {
        "time_stretch": 0.97,
        "pitch_shift": 0.0,
        "highpass_hz": 30,
        "lowpass_hz": 15000,
        "bass_db": 1.5,
        "highshelf_freq": 14000,
        "highshelf_db": -0.5,
        "saturation": 0.3,
        "compression": 0.15,
        "bitcrush": 0.0,
        "wow_flutter": 0.1,
        "stereo_width": 1.0,
        "noise": 0.03,
        "reverb": 0.1,
        "limiter": 0.95,
    },
    "Nostalgic 90s": {
        "time_stretch": 0.88,
        "pitch_shift": -2.5,
        "highpass_hz": 40,
        "lowpass_hz": 8000,
        "bass_db": 2.0,
        "highshelf_freq": 6000,
        "highshelf_db": -6.0,
        "saturation": 0.5,
        "compression": 0.4,
        "bitcrush": 0.35,
        "wow_flutter": 0.15,
        "stereo_width": 0.9,
        "noise": 0.08,
        "reverb": 0.12,
        "limiter": 0.9,
    },
    "Late Night Drive": {
        "time_stretch": 0.94,
        "pitch_shift": -1.5,
        "highpass_hz": 30,
        "lowpass_hz": 13000,
        "bass_db": 3.5,
        "highshelf_freq": 11000,
        "highshelf_db": -1.5,
        "saturation": 0.4,
        "compression": 0.25,
        "bitcrush": 0.0,
        "wow_flutter": 0.2,
        "stereo_width": 1.3,
        "noise": 0.04,
        "reverb": 0.25,
        "limiter": 0.95,
    },
    "Jazz Cafe": {
        "time_stretch": 0.96,
        "pitch_shift": -0.5,
        "highpass_hz": 30,
        "lowpass_hz": 13000,
        "bass_db": 2.0,
        "highshelf_freq": 11000,
        "highshelf_db": -1.0,
        "saturation": 0.35,
        "compression": 0.2,
        "bitcrush": 0.0,
        "wow_flutter": 0.3,
        "stereo_width": 1.0,
        "noise": 0.1,
        "reverb": 0.3,
        "limiter": 0.95,
    },
    "Dreamy Clouds": {
        "time_stretch": 0.93,
        "pitch_shift": -1.0,
        "highpass_hz": 30,
        "lowpass_hz": 12000,
        "bass_db": 1.0,
        "highshelf_freq": 10000,
        "highshelf_db": -1.5,
        "saturation": 0.25,
        "compression": 0.12,
        "bitcrush": 0.0,
        "wow_flutter": 0.18,
        "stereo_width": 1.4,
        "noise": 0.02,
        "reverb": 0.6,
        "limiter": 0.95,
    },
    "VHS Memory": {
        "time_stretch": 0.89,
        "pitch_shift": -3.5,
        "highpass_hz": 50,
        "lowpass_hz": 8000,
        "bass_db": 1.5,
        "highshelf_freq": 6000,
        "highshelf_db": -7.0,
        "saturation": 0.7,
        "compression": 0.35,
        "bitcrush": 0.25,
        "wow_flutter": 0.6,
        "stereo_width": 0.7,
        "noise": 0.2,
        "reverb": 0.2,
        "limiter": 0.9,
    },
    "Coffee Shop": {
        "time_stretch": 0.98,
        "pitch_shift": 0.0,
        "highpass_hz": 30,
        "lowpass_hz": 14000,
        "bass_db": 1.8,
        "highshelf_freq": 13000,
        "highshelf_db": -0.5,
        "saturation": 0.25,
        "compression": 0.18,
        "bitcrush": 0.0,
        "wow_flutter": 0.12,
        "stereo_width": 1.1,
        "noise": 0.05,
        "reverb": 0.25,
        "limiter": 0.95,
    },
    "Midnight Radio": {
        "time_stretch": 0.91,
        "pitch_shift": -2.0,
        "highpass_hz": 500,
        "lowpass_hz": 4000,
        "bass_db": -1.0,
        "highshelf_freq": 3000,
        "highshelf_db": -5.0,
        "saturation": 0.65,
        "compression": 0.5,
        "bitcrush": 0.15,
        "wow_flutter": 0.25,
        "stereo_width": 0.5,
        "noise": 0.25,
        "reverb": 0.15,
        "limiter": 0.9,
    },
    "Sunset Beach": {
        "time_stretch": 0.95,
        "pitch_shift": -1.0,
        "highpass_hz": 30,
        "lowpass_hz": 12500,
        "bass_db": 2.5,
        "highshelf_freq": 10000,
        "highshelf_db": -1.5,
        "saturation": 0.45,
        "compression": 0.22,
        "bitcrush": 0.0,
        "wow_flutter": 0.22,
        "stereo_width": 1.25,
        "noise": 0.06,
        "reverb": 0.45,
        "limiter": 0.95,
    },
}
